# organize config as obj file:
#     - firstly define the vertices (Joints) section
#     - then define the edges between them (referring to their id)
---
n_dims: 2
Joints:  
    - id: 0
      angles: [0, 0, 0] 
      actuators:     
          - type: Z_AXIS_MOTOR
            constraints:         
              min: -.inf 
              max: .inf
    - id: 1
      angles: [0, 0, 0] 
      actuators: 
          - type: Z_AXIS_MOTOR
            constraints:         
              min: -.inf 
              max: .inf
    - id: 2
      angles: [0, 0, 0]          
      actuators: []
Geometry:
  vertices: [
    [0, 0, 0],
    [10, 0, 0],
    [20, 0, 0]    
  ]
  edges: [
    [1], [2], []
  ]
  leaf_joint: [2]