# organize config as obj file:
#     - firstly define the vertices (Joints) section
#     - then define the edges between them (referring to their id)
---
Joints:  
    - id: 0
      actuators:     
          - type: ROTARY_ACTUATOR
            axis: 2
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 1
      actuators: 
          - type: ROTARY_ACTUATOR
            axis: 0
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 2
      actuators: []
Geometry:
    vertices:
      coords: [
        [0, 0, 0],
        [0, 0, 10],
        [0, 0, 20]    
      ]
      angles: [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0] 
      ]
  edges: [
    [1], [2], []
  ]
  leaf_joint: [2]