# organize config as obj file:
#     - firstly define the vertices (Joints) section
#     - then define the edges between them (referring to their id)
---
n_dims: 3
Joints:  
    - id: 0
      actuators:     
          - type: Z_AXIS_MOTOR
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 1
      actuators:   
          - type: X_AXIS_MOTOR
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 2
      actuators: 
          - type: X_AXIS_MOTOR
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 3
      actuators: 
          - type: X_AXIS_MOTOR
            start_angle: 0
            constraints:         
              min: -.inf 
              max: .inf
    - id: 4
      actuators: []
Geometry:
  vertices:
      coords: [
        [0, 0, 0],
        [0, 0, 1],
        [0, 0, 10],
        [0, 0, 15],
        [0, 0, 20]    
      ]
      angles: [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]    
      ]
  edges: [
    [1], [2], [3], [4], []
  ]
  leaf_joint: [4]